//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstREST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public string CodArtigo { get; set; }
        public string DescArtigo { get; set; }
        public string ArmazemArtigo { get; set; }
        public int QuantidadeArtigo { get; set; }
        public double PrecoArtigo { get; set; }
        public int STKAtualArtigo { get; set; }
    
        public virtual User User { get; set; }
    }
}
